baseURL = "https://unnawut.com/"
languageCode = "th-th"
title = "Unnawut Leepaisalsuwanna"
theme = "book"
pygmentsCodeFences = true

[taxonomies]
  tag = "tags"

[params]
  BookToC = 3
  BookSection = '*'
  BookSearch = true
