# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Unnawut"
license = "MIT"
licenselink = "https://github.com/unnawut/personal-site-v2/blob/master/LICENSE.md"
homepage = "https://github.com/unnawut/personal-site-v2"
min_version = "0.41"

[author]
  name = "Unnawut Leepaisalsuwanna"
  homepage = "https://unnawut.com"
